imports:
    - php
inherit: true
tools:
    #See appveyor.yml.
    external_code_coverage:
       runs: 14
       timeout: 2520
    php_sim: false
    php_cpd: true
    php_code_sniffer:
        config:
            standard: PEAR