language: php
php:
  # The earliest PHP 5.3 version that can run the test suit
  # AND is supported by Travis-CI.
  #- 5.3.3
  - 5.3
  - 5.4
  - 5.5
before_script:
  - composer self-update
  - composer install --dev
  - cd tests
  - ../vendor/bin/phpunit --configuration secondaryPeer.xml > secondaryPeer.out.txt &
  - sleep 2
script:
  - ../vendor/bin/phpunit --configuration phpunit.xml
after_script:
  - cat secondaryPeer.out.txt