language: php
php:
  # The earliest PHP 5.3 version that can run the test suit
  # AND is supported by Travis-CI.
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
before_script:
  - composer self-update
  - composer install
  - composer require "pear2/cache_shm" ">=0.1.2"
  - cd tests
  - phpunit --configuration secondaryPeer.xml &
  - sleep 2
script:
  - phpunit --configuration phpunit.xml